sudo: required

services:
  - docker

before_install:
  - docker build -t erkant/frontend-ci:0.1 -f Dockerfile.dev .

script:
  - docker run erkant/frontend-ci:0.1 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: DockerReact
  env: DockerReact-env
  bucket_name: elasticbeanstalk-eu-west-2-137285279425
  bucket_path: DockerReact
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
    
